server {
    listen 8080 default_server;
    server_name _;

    error_log  /dev/stderr warn;
    access_log /dev/stdout combined;

	# include the default pages
	include /etc/nginx/includes/shared-error-pages.conf;
	
    location = /healthz {
        access_log off;
        add_header Content-Type text/plain;
        return 200 "ok\n";
    }

    location = /favicon.ico {
        access_log off;
        add_header Content-Type text/plain;
        return 200 "ok\n";
    }

    location / {
        return 403 "sorry!";
        # optional: return 444;
    }
}

