# alqabasy.com
server {
    listen 8080;
    server_name
    	# main
        alqabasy.com
        www.alqabasy.com

        # buissness
		api.alqabasy.com
		dash.alqabasy.com
		drivers.alqabasy.com

		# s3 storage, s3 console
		s3.alqabasy.com
		s3c.alqabasy.com;

    return 301 https://$host$request_uri;
}


# mahros.dev
server {
	listen 8080;
	server_name
		# main
		mahros.dev
		wwww.mahros.dev

		# api
		api.mahros.dev
		dash.mahros.dev

		# storage
		s3.mahros.dev
		s3c.mahros.dev;

	return 301 https://$host$request_uri;
}

# petrocortex.com 
server {
    listen 8080;
    server_name
    	# main
		petrocortex.com
		www.petrocortex.com;


    return 301 https://$host$request_uri;
}

# petrocortex.io
server {
    listen 8080;
    server_name
    	# main
		petrocortex.io
		www.petrocortex.io

		# api
		api.petrocortex.io
		dash.petrocortex.io
		com.petrocortex.io

		# s3 storage, s3 console
		s3.petrocortex.io

		*.petrocortex.io;


    return 301 https://$host$request_uri;
}

# obsura.one
server {
    listen 8080;
    server_name
		# main
		obsura.one
		www.obsura.one

		# api
		api.obsura.one
		demo.obsura.one;
		
    return 301 https://$host$request_uri;
}



# qabas.one
server {
	listen 8080;
	server_name
		# main
		qabas.one
		www.qabas.one

		*.qabas.one;

	return 301 https://$host$request_uri;
}

# flytics.org
server {
	listen 8080;
	server_name
		# main
		flytics.org
		www.flytics.org

		*.flytics.org;

	return 301 https://$host$request_uri;
}
