server {
    listen 8443 ssl default_server;
    http2 on;
    
    server_name _;

    ssl_certificate     /etc/nginx/certs/mahrostack.local.pem;
    ssl_certificate_key /etc/nginx/certs/mahrostack.local-key.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    error_log  /dev/stderr warn;
    access_log /dev/stdout combined;


	include /etc/nginx/includes/shared-error-pages.conf;

	add_header X-Content-Type-Options nosniff always;
	add_header X-Frame-Options DENY always;
	add_header Referrer-Policy strict-origin-when-cross-origin always;
	add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;

	
    return 403;
}
